version: '3.8'

services:
  sygus-planner:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - MODEL_NAME=${MODEL_NAME}
    command: /bin/bash
    stdin_open: true
    tty: true
